# Generated by Django 3.1.7 on 2021-05-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceresponse',
            unique_together={('email', 'attendance_request')},
        ),
    ]
