# Generated by Django 3.1.7 on 2021-05-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_notificationdetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceresponse',
            unique_together=set(),
        ),
    ]
